-- ---------------------------------------------------------------------------
--  AUREA · Italia Roleplay — catalogo oggetti dentro la tabella ESX `items`
--
--  Serve SOLO in modalità "AUREA su ESX" ([esx]/aurea_esx), e serve a una
--  cosa sola: che gli script esx_* trovino l'oggetto quando ne cercano
--  l'etichetta o il peso. L'inventario vero resta aurea_inventory, con i
--  suoi slot e le sue metadata per istanza — senza quelle cadrebbero la
--  purezza della droga, le matricole delle armi, i reperti e i documenti.
--
--  In modalità [esx]/es_extended questo file NON serve: il catalogo lo
--  legge da aurea_core/shared/item.lua, che è la fonte unica.
--
--  Generato da aurea_core/shared/item.lua.
--
--  Esecuzione:
--      mysql -u utente -p nome_database < sql/esx/02_oggetti.sql
-- ---------------------------------------------------------------------------

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `items` (
  `name`   VARCHAR(50) NOT NULL,
  `label`  VARCHAR(50) NOT NULL,
  `weight` INT NOT NULL DEFAULT 1,
  `rare`   TINYINT(1) NOT NULL DEFAULT 0,
  `can_remove` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
  ('carta_identita', 'Carta d\'identità', 5, 1, 1),
  ('patente', 'Patente di guida', 5, 1, 1),
  ('tessera_sanitaria', 'Tessera sanitaria', 5, 1, 1),
  ('libretto', 'Libretto di circolazione', 10, 1, 1),
  ('assicurazione', 'Certificato assicurativo', 5, 1, 1),
  ('porto_armi', 'Porto d\'armi', 5, 1, 1),
  ('tesserino', 'Tesserino di servizio', 5, 1, 1),
  ('visura', 'Visura camerale', 20, 1, 1),
  ('fattura', 'Fattura', 5, 1, 1),
  ('verbale', 'Verbale di contestazione', 5, 1, 1),
  ('tesserino_stampa', 'Tesserino da giornalista', 5, 1, 1),
  ('giornale', 'Quotidiano', 60, 0, 1),
  ('telefono', 'Smartphone', 180, 1, 1),
  ('radio', 'Radio ricetrasmittente', 400, 1, 1),
  ('laptop', 'Portatile', 1800, 1, 1),
  ('gps_tracker', 'Localizzatore GPS', 90, 0, 1),
  ('jammer', 'Disturbatore di frequenze', 900, 1, 1),
  ('powerbank', 'Batteria portatile', 250, 0, 1),
  ('componenti_elettronici', 'Componenti elettronici', 120, 0, 1),
  ('acqua', 'Acqua naturale 0,5L', 520, 0, 1),
  ('acqua_frizzante', 'Acqua frizzante 0,5L', 520, 0, 1),
  ('espresso', 'Caffè espresso', 60, 0, 1),
  ('cappuccino', 'Cappuccino', 220, 0, 1),
  ('spritz', 'Spritz', 300, 0, 1),
  ('vino_rosso', 'Vino rosso', 1250, 0, 1),
  ('vino_docg', 'Vino DOCG', 1250, 1, 1),
  ('birra', 'Birra artigianale', 660, 0, 1),
  ('amaro', 'Amaro', 200, 0, 1),
  ('panino', 'Panino', 250, 0, 1),
  ('pizza_margherita', 'Pizza margherita', 550, 0, 1),
  ('pasta_carbonara', 'Pasta alla carbonara', 450, 0, 1),
  ('cornetto', 'Cornetto', 90, 0, 1),
  ('parmigiano_dop', 'Parmigiano Reggiano DOP', 1000, 1, 1),
  ('mozzarella_bufala', 'Mozzarella di bufala', 250, 0, 1),
  ('olio_extravergine', 'Olio extravergine', 950, 0, 1),
  ('olio_dop', 'Olio EVO DOP', 950, 1, 1),
  ('uva_sangiovese', 'Uva Sangiovese', 900, 0, 1),
  ('uva_nebbiolo', 'Uva Nebbiolo', 900, 0, 1),
  ('mosto', 'Mosto', 1200, 0, 1),
  ('olive', 'Olive', 800, 0, 1),
  ('latte_crudo', 'Latte crudo', 1030, 0, 1),
  ('caglio', 'Caglio', 200, 0, 1),
  ('formaggio_fresco', 'Formaggio fresco', 700, 0, 1),
  ('caffe_verde', 'Caffè verde', 500, 0, 1),
  ('caffe_tostato', 'Caffè tostato', 480, 0, 1),
  ('farina_00', 'Farina 00', 1000, 0, 1),
  ('impasto_pizza', 'Panetto di impasto', 280, 0, 1),
  ('pomodoro_san_marzano', 'Pomodoro San Marzano', 800, 0, 1),
  ('tessuto_pregiato', 'Tessuto pregiato', 600, 0, 1),
  ('capo_sartoriale', 'Capo sartoriale', 900, 1, 1),
  ('rame', 'Rame', 400, 0, 1),
  ('acciaio', 'Acciaio', 700, 0, 1),
  ('plastica', 'Plastica', 200, 0, 1),
  ('vetro', 'Vetro', 500, 0, 1),
  ('canna_pesca', 'Canna da pesca', 1400, 1, 1),
  ('esca_semplice', 'Esca', 30, 0, 1),
  ('esca_pregiata', 'Esca artificiale', 40, 0, 1),
  ('piccone', 'Piccone', 3200, 1, 1),
  ('orata', 'Orata', 600, 0, 1),
  ('branzino', 'Branzino', 700, 0, 1),
  ('sgombro', 'Sgombro', 400, 0, 1),
  ('tonno', 'Tonno', 9000, 1, 1),
  ('polpo', 'Polpo', 900, 0, 1),
  ('trota', 'Trota', 500, 0, 1),
  ('luccio', 'Luccio', 1800, 0, 1),
  ('carpa', 'Carpa', 1500, 0, 1),
  ('dattero', 'Dattero di mare', 120, 0, 1),
  ('carne_cinghiale', 'Carne di cinghiale', 2500, 0, 1),
  ('carne_cervo', 'Carne di cervo', 3000, 0, 1),
  ('carne_lepre', 'Carne di lepre', 900, 0, 1),
  ('pietra', 'Pietrisco', 1500, 0, 1),
  ('quarzo', 'Quarzo', 800, 0, 1),
  ('oro_grezzo', 'Oro grezzo', 400, 0, 1),
  ('porcini', 'Funghi porcini', 350, 0, 1),
  ('tartufo_nero', 'Tartufo nero', 90, 0, 1),
  ('tartufo_bianco', 'Tartufo bianco d\'Alba', 80, 1, 1),
  ('castagne', 'Castagne', 700, 0, 1),
  ('erbe_officinali', 'Erbe officinali', 120, 0, 1),
  ('licenza', 'Licenza', 5, 1, 1),
  ('kit_medico', 'Kit medico', 1200, 0, 1),
  ('bendaggio', 'Bendaggio', 120, 0, 1),
  ('antidolorifico', 'Antidolorifico', 40, 0, 1),
  ('adrenalina', 'Adrenalina', 90, 0, 1),
  ('stecca', 'Stecca ortopedica', 300, 0, 1),
  ('sacca_sangue', 'Sacca di sangue', 500, 0, 1),
  ('manette', 'Manette', 450, 0, 1),
  ('etilometro', 'Etilometro', 600, 0, 1),
  ('telelaser', 'Telelaser', 1500, 0, 1),
  ('kit_rilievi', 'Kit rilievi', 2200, 0, 1),
  ('paletta', 'Paletta segnaletica', 300, 0, 1),
  ('spray_urticante', 'Spray urticante', 150, 0, 1),
  ('dissuasore', 'Striscia chiodata', 4000, 0, 1),
  ('grimaldello', 'Grimaldello', 120, 0, 1),
  ('chiave_inglese', 'Chiave inglese', 800, 0, 1),
  ('contanti_sporchi', 'Contanti non tracciati', 2, 0, 1),
  ('cartuccia', 'Cartucce', 12, 0, 1),
  ('cartuccia_caccia', 'Cartucce da caccia', 20, 0, 1),
  ('arma', 'Arma da fuoco', 1200, 1, 1),
  ('sostanza_grezza', 'Sostanza grezza', 30, 0, 1),
  ('seme', 'Semi', 15, 0, 1),
  ('annaffiatoio', 'Annaffiatoio', 900, 1, 1),
  ('sostanza_raffinata', 'Sostanza raffinata', 25, 0, 1),
  ('documento_falso', 'Documento contraffatto', 5, 1, 1),
  ('targa_clonata', 'Targa clonata', 300, 1, 1),
  ('infiorescenza', 'Infiorescenza', 20, 0, 1),
  ('hashish', 'Hashish', 18, 0, 1),
  ('cocaina', 'Cocaina', 12, 0, 1),
  ('eroina', 'Eroina', 12, 0, 1),
  ('mdma', 'MDMA', 10, 0, 1),
  ('erba', 'Marijuana', 15, 0, 1),
  ('pasta_base', 'Pasta base di coca', 40, 0, 1),
  ('oppio_grezzo', 'Oppio grezzo', 40, 0, 1),
  ('precursori', 'Precursori chimici', 350, 0, 1),
  ('solvente', 'Solvente', 500, 0, 1),
  ('mannitolo', 'Mannitolo', 25, 0, 1),
  ('lattosio', 'Lattosio', 25, 0, 1),
  ('caffeina', 'Caffeina', 20, 0, 1),
  ('bilancino', 'Bilancino di precisione', 300, 1, 1),
  ('narcotest', 'Kit narcotest', 80, 0, 1),
  ('centralina', 'Centralina clonata', 400, 1, 1),
  ('spadino', 'Spadino elettronico', 250, 1, 1),
  ('antifurto', 'Antifurto satellitare', 200, 0, 1),
  ('tronchesi', 'Tronchesi', 1100, 0, 1),
  ('muta', 'Muta subacquea', 3500, 1, 1),
  ('esplosivo', 'Carica esplosiva', 2200, 1, 1),
  ('fotocamera', 'Fotocamera', 700, 1, 1),
  ('lingotto', 'Lingotto d\'oro', 12000, 0, 1),
  ('quadro', 'Dipinto d\'autore', 4000, 1, 1),
  ('contabilita', 'Libro mastro del clan', 800, 1, 1),
  ('boombox', 'Stereo portatile', 3200, 1, 1),
  ('fiches', 'Fiches', 8, 0, 1),
  ('guinzaglio', 'Guinzaglio', 200, 1, 1),
  ('crocchette', 'Crocchette', 800, 0, 1),
  ('ricetta', 'Ricetta medica', 5, 1, 1),
  ('antibiotico', 'Antibiotico', 40, 0, 1),
  ('ansiolitico', 'Ansiolitico', 30, 0, 1),
  ('disinfettante', 'Disinfettante', 180, 0, 1),
  ('biglietto', 'Titolo di viaggio', 3, 1, 1),
  ('tagliando_sosta', 'Tagliando di sosta', 3, 1, 1),
  ('pizza_marinara', 'Pizza marinara', 550, 0, 1),
  ('prosciutto', 'Prosciutto', 300, 0, 1),
  ('pasta_secca', 'Pasta secca', 500, 0, 1),
  ('caffe_crudo', 'Caffè in grani', 250, 0, 1),
  ('guanti', 'Guanti in nitrile', 20, 0, 1),
  ('tampone_dna', 'Tampone sterile', 15, 0, 1),
  ('reperto', 'Reperto sigillato', 120, 1, 1),
  ('certificato_medico', 'Certificato medico', 5, 1, 1),
  ('kit_riparazione', 'Kit riparazione', 2500, 0, 1),
  ('tanica', 'Tanica di carburante', 8000, 1, 1),
  ('cavi_avviamento', 'Cavi di avviamento', 1500, 0, 1),
  ('corda', 'Corda', 900, 0, 1),
  ('borsone', 'Borsone', 1500, 1, 1),
  ('valigetta', 'Valigetta', 1200, 1, 1),
  ('chiavi_casa', 'Mazzo di chiavi', 60, 1, 1),
  ('biglietto_lotteria', 'Gratta e vinci', 5, 0, 1)
ON DUPLICATE KEY UPDATE `label` = VALUES(`label`), `weight` = VALUES(`weight`), `rare` = VALUES(`rare`);
